FROM forgejo.develop.10.199.64.20.nip.io/root/alpine:3.24
# Alpine's apk is native here. The repository URL is set at test time by
# scripts/apk.sh (dl-cdn.alpinelinux.org, intercepted by the spoofed proxy).
