ARG BASE_IMAGE=forgejo.develop.10.199.64.20.nip.io/easylab/toolchain-base:latest
FROM ${BASE_IMAGE}
ARG EASYLAB=http://easylab.temp.svc.cluster.local
RUN mkdir -p /opt/helm && curl -fsSL -o /tmp/helm.tgz "${EASYLAB}/pkgs/generic/helm/4.3.0/helm-v4.3.0-linux-amd64.tar.gz" \
 && tar -xzf /tmp/helm.tgz -C /tmp && mv /tmp/linux-amd64/helm /opt/helm/helm && rm -rf /tmp/helm.tgz /tmp/linux-amd64
ENV PATH=/opt/helm:$PATH
