FROM forgejo.develop.10.199.64.20.nip.io/easylab/toolchain-base:latest
ARG EASYLAB=http://easylab.temp.svc.cluster.local
RUN curl -fsSL -o /tmp/miniconda.sh "${EASYLAB}/pkgs/generic/miniconda/latest/Miniconda3-latest-Linux-x86_64.sh" \
 && bash /tmp/miniconda.sh -b -p /opt/miniconda && rm /tmp/miniconda.sh
ENV PATH=/opt/miniconda/bin:$PATH
