FROM forgejo.develop.10.199.64.20.nip.io/easylab/toolchain-base:latest
ARG EASYLAB=http://easylab.temp.svc.cluster.local
RUN mkdir -p /opt/regctl && curl -fsSL -o /opt/regctl/regctl "${EASYLAB}/pkgs/generic/regctl/0.11.6/regctl-linux-amd64" && chmod +x /opt/regctl/regctl \
 && mkdir -p /opt/skopeo && curl -fsSL -o /opt/skopeo/skopeo "${EASYLAB}/pkgs/generic/skopeo/1.24.0/skopeo-linux-amd64" && chmod +x /opt/skopeo/skopeo
ENV PATH=/opt/regctl:/opt/skopeo:$PATH
